version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./out s3://code-build-frontend --delete

artifacts:
  files:
    - 'frontend/./next/**/*'
    - 'frontend/public/**/*'
    - 'frontend/package.json'

  cache:
    paths:
      - 'frontend/node_modules/**/*'
      - 'frontend/.next/cache/**/*'
