version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - cd frontend
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./out s3://code-build-frontend --delete

artifacts:
  files:
    - '.next/**/*'
    - 'public/**/*'
    - 'package.json'

cache:
  paths:
    - 'node_modules/**/*'
    - '.next/cache/**/*'
