version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync out s3://sk-unailit/frontend --delete

artifacts:
  files:
    - '**/*'
  base-directory: out
